<?php
$title = "Cập nhật ";
$this->headTitle($title);

$form->get("ten_dang_nhap")-> setAttributes([
    'readonly' => true,
]);

$form->prepare();
?>


<h1><?= $this->escapeHtml($title) ."[". $this->escapeHtml($user->getTenDangNhap())."]"     ?></h1>
<hr>
<?= $this->form()->openTag($form) ?>

<div class="form-group">
    <?= $this->formLabel($form->get('ten_dang_nhap')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('ten_dang_nhap')); ?>
        <?= $this->formElementErrors($form->get('ten_dang_nhap')); ?>
    </div>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('email')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>
    </div>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('diem_cao_nhat')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('diem_cao_nhat')); ?>
    </div>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('credit')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('credit')); ?>
    </div>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('hinh_dai_dien')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('hinh_dai_dien')); ?>
    </div>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('trang_thai')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('trang_thai')); ?>
    </div>
</div>

<div class="form-group">
   
    <div class="col-sm-9">
        <?= $this->formElement($form->get('btnSubmit')); ?>
    </div>
</div>

<?= $this->form()->openTag($form) ?>