<?php
$this->headTitle("Đổi mật khẩu");
$form->prepare();
?>

<h1><?= $this->escapeHtml("Đổi mật khẩu") ?></h1>
<div><?= $this->flashMessenger()->render('error',['alert','alert-danger']);?><div>
<div><?= $this->flashMessenger()->render('success',['alert','alert-success']);?><div>

<hr>

<?= $this->form()->openTag($form) ?>


<div class="form-group">
    <?= $this->formLabel($form->get('email')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>
    </div>
</div>


<div class="form-group">
    <?= $this->formLabel($form->get('captcha_image')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('captcha_image')); ?>
        <?= $this->formElementErrors($form->get('captcha_image')); ?>
    </div>
</div>
<?php echo $this->formElement($form->get('csrf')); 
?>
<div class="form-group">

    <div class="col-sm-9">
        <?= $this->formElement($form->get('btnSubmit')); ?>
    </div>
</div>

<?= $this->form()->openTag($form) ?>
