<?php
$this->headTitle("Reset mật khẩu");
$form->prepare();
?>

<h1><?= $this->escapeHtml("Reset Mật khẩu") ?></h1>
<div><?= $this->flashMessenger()->render('error',['alert','alert-danger']);?><div>
<hr>

<?= $this->form()->openTag($form) ?>




<div class="form-group">
    <?= $this->formLabel($form->get('new_pw')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('new_pw')); ?>
        <?= $this->formElementErrors($form->get('new_pw')); ?>
    </div>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('confirm_new_pw')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('confirm_new_pw')); ?>
        <?= $this->formElementErrors($form->get('confirm_new_pw')); ?>
    </div>
</div>
<?php echo $this->formElement($form->get('csrf')); 
?>
<div class="form-group">

    <div class="col-sm-9">
        <?= $this->formElement($form->get('btnSubmit')); ?>
    </div>
</div>

<?= $this->form()->openTag($form) ?>
