<?php
$title = "Đăng nhập";
$this->headTitle($title);
$form->prepare();
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<hr>
<?= $this->form()->openTag($form) ?>

<div class="form-group">
    <?= $this->formLabel($form->get('ten_dang_nhap')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('ten_dang_nhap')); ?>
        <?= $this->formElementErrors($form->get('ten_dang_nhap')); ?>
    </div>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('mat_khau')); ?>
    <div class="col-sm-9">
        <?= $this->formElement($form->get('mat_khau')); ?>
        <?= $this->formElementErrors($form->get('mat_khau')); ?>
    </div>
</div>

<div class="form-group">
   
    <div class="col-sm-9">
        <?= $this->formElement($form->get('ghi_nho')); ?>
        <?= $this->formLabel($form->get('ghi_nho')); ?>
        <?= $this->formElementErrors($form->get('ghi_nho')); ?>
    </div>
</div>

<div class="form-group">

    <div class="col-sm-9">
        <?= $this->formElement($form->get('btnSubmit')); ?>
    </div>
</div>

<?= $this->form()->openTag($form) ?>