<?php

$title = 'Thêm câu hỏi';
$this->headTitle($title);
$form->prepare();
?>
<div class='card'>
    <div class='card-header'>
        <div class='card-title'>
            <h2><?= $this->escapeHtml($title) ?></h2>
        </div>
    </div>
    <div class='card-body'>
        <?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']) ?>
    </div>

    <div class="container-fluid">
        <div class='row'>
            <div class="col-md-12 col-md-offset-3">
                <?= $this->form()->openTag($form) ?>
                <div class="form-group">
                    <?= $this->formLabel($form->get('id_linh_vuc')); ?>
                    <div class="col-md-6">
                        <?php
                        echo $this->formElement($form->get('id_linh_vuc'));
                        echo $this->formElementErrors($form->get('id_linh_vuc'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('noi_dung')); ?>
                    <div class="col-md-6">
                        <?php
                        echo $this->formElement($form->get('noi_dung'));
                        echo $this->formElementErrors($form->get('noi_dung'));
                        ?>
                    </div>
                </div>
                <div class='form-inline'>

                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('phuong_an_A')); ?>
                    <div class="col-md-3">
                        <?php
                        echo $this->formElement($form->get('phuong_an_A'));
                        echo $this->formElementErrors($form->get('phuong_an_A'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('phuong_an_B')); ?>
                    <div class="col-md-3">
                        <?php
                        echo $this->formElement($form->get('phuong_an_B'));
                        echo $this->formElementErrors($form->get('phuong_an_B'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('phuong_an_C')); ?>
                    <div class="col-md-3">
                        <?php
                        echo $this->formElement($form->get('phuong_an_C'));
                        echo $this->formElementErrors($form->get('phuong_an_C'));
                        ?>
                    </div>
                    <?= $this->formLabel($form->get('phuong_an_D')); ?>
                    <div class="col-md-3">
                        <?php
                        echo $this->formElement($form->get('phuong_an_D'));
                        echo $this->formElementErrors($form->get('phuong_an_D'));
                        ?>
                    </div>


                    <div class="form-group">

                    </div>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('dap_an')); ?>
                    <div class="col-md-9">
                        <?php
                        echo $this->formElement($form->get('dap_an'));
                        echo $this->formElementErrors($form->get('dap_an'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <!--?=$this->formLabel($form->get('save')); ?-->

                    <div class="col-md-3">
                        <?php
                        echo $this->formElement($form->get('save'));
                        echo $this->formElementErrors($form->get('save'));
                        ?>
                    </div>

                </div>
                <!-- <div class="form-group">
            <!--?=$this->formLabel($form->get('save')); ?-->
                <!-- <div class="col-md-9">
                <?php
                // echo $this->formElement($form->get('image'));
                // echo $this->formElementErrors($form->get('image'));
                ?>
                </div>
        </div> -->
            </div>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
</div>